import { Router } from 'express';
import { analyticsRouter } from './analytics.routes.js';
import { attendanceRouter } from './attendance.routes.js';
import { authRouter } from './auth.routes.js';
import { customerRouter } from './customer.routes.js';
import { dailyReportRouter } from './dailyReport.routes.js';
import { documentRouter } from './document.routes.js';
import { inventoryRouter } from './inventory.routes.js';
import { invoiceRouter } from './invoice.routes.js';
import { leadRouter } from './lead.routes.js';
import { locationRouter } from './location.routes.js';
import { notificationRouter } from './notification.routes.js';
import { orderRouter } from './order.routes.js';
import { paymentRouter } from './payment.routes.js';
import { productRouter } from './product.routes.js';
import { quotationRouter } from './quotation.routes.js';
import { reminderRouter } from './reminder.routes.js';
import { targetRouter } from './target.routes.js';
import { userRouter } from './user.routes.js';
import { visitRouter } from './visit.routes.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/customers', customerRouter);
apiRouter.use('/products', productRouter);
apiRouter.use('/inventory', inventoryRouter);
apiRouter.use('/leads', leadRouter);
apiRouter.use('/locations', locationRouter);
apiRouter.use('/location', locationRouter);
apiRouter.use('/orders', orderRouter);
apiRouter.use('/quotations', quotationRouter);
apiRouter.use('/invoices', invoiceRouter);
apiRouter.use('/visits', visitRouter);
apiRouter.use('/daily-reports', dailyReportRouter);
apiRouter.use('/attendance', attendanceRouter);
apiRouter.use('/targets', targetRouter);
apiRouter.use('/reminders', reminderRouter);
apiRouter.use('/documents', documentRouter);
apiRouter.use('/payments', paymentRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/reports', dailyReportRouter);